-- MySQL Script generated by MySQL Workbench
-- Fri May 18 22:57:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ProductCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductCategory` (
  `categoryId` INT NOT NULL,
  `categoryName` VARCHAR(64) NOT NULL,
  `categoryType` INT NOT NULL,
  PRIMARY KEY (`categoryId`),
  INDEX `index_category_type` (`categoryType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_info` (
  `product_id` VARCHAR(32) NOT NULL,
  `product_name` VARCHAR(64) NOT NULL,
  `product_price` DECIMAL(8,2) NOT NULL,
  `product_description` VARCHAR(64) NULL,
  `product_icon` VARCHAR(512) NULL,
  `product_stock` INT NOT NULL DEFAULT 0,
  `category_type` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_type_idx` (`category_type` ASC),
  CONSTRAINT `category_type`
    FOREIGN KEY (`category_type`)
    REFERENCES `mydb`.`ProductCategory` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_master` (
  `order_id` VARCHAR(32) NOT NULL,
  `desk_id` INT NOT NULL,
  `buyer_openid` VARCHAR(64) NOT NULL,
  `order_amount` DECIMAL(8,2) NOT NULL,
  `order_status` TINYINT(3) NOT NULL,
  `pay_status` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`),
  INDEX `index_buyer_openid` (`buyer_openid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_detail` (
  `detail_id` VARCHAR(32) NOT NULL,
  `order_id` VARCHAR(32) NOT NULL,
  `product_quantity` INT NOT NULL,
  `product_info_product_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`detail_id`),
  INDEX `index_order_id` (`order_id` ASC),
  INDEX `fk_order_detail_product_info1_idx` (`product_info_product_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order_master` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_product_info1`
    FOREIGN KEY (`product_info_product_id`)
    REFERENCES `mydb`.`product_info` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
