spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/e-order?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
      show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
server:
  context-path: /eorder